MyNewsApp
SklRV/MyNewsApp pull request #1
Opened 2021-11-16 22:15 UTC by SklRV

2021-11-20 22:14 UTC, mist962 requested changes

2021-11-20 22:14 UTC, mist962 commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
все должно быть разделено тегами //Lifecicle

2021-11-20 22:14 UTC, mist962 commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
//Navigation и тд в зависимости от набора библиотек

2021-11-20 22:14 UTC, mist962 commented on app/src/main/AndroidManifest.xml
>          android:allowBackup="true"
false

2021-11-20 22:14 UTC, mist962 commented on app/src/main/java/com/example/mynewsapp/NewsApp.kt
> +
empty line

2021-11-20 22:14 UTC, mist962 commented on app/src/main/java/com/example/mynewsapp/login_and_registration/LoginFragment.kt
> +        binding?.apply {
with(binding) {

2021-11-20 22:14 UTC, mist962 commented on app/src/main/java/com/example/mynewsapp/login_and_registration/LoginFragment.kt
> +                userViewModel.getLoginDetails(requireContext(), roomUsername, roomPassword)!!
!! не используем, может привести к вылетам

2021-11-20 22:14 UTC, mist962 commented on app/src/main/java/com/example/mynewsapp/ui/dashboard/DashboardFragment.kt
> +        }
путо, удали код

2021-11-20 22:14 UTC, mist962 commented on app/src/main/java/com/example/mynewsapp/ui/notifications/NotificationsFragment.kt
> +        }
можно удалит метод

2021-11-20 22:14 UTC, mist962 commented on app/src/main/res/values/strings.xml
> +    <string name="text_notifications">Meow!</string>
должно быть разделено тегом коментария <--Название экрана--/>

2021-11-20 22:14 UTC, mist962 commented on app/src/main/res/layout/list_item_news.xml
> +    <LinearLayout
Выглядит лишней вложенностью

2021-11-21 00:07 UTC, SklRV commented on app/src/main/java/com/example/mynewsapp/login_and_registration/LoginFragment.kt
> +        binding?.apply {
Не понял

2021-11-21 09:00 UTC, mist962 requested changes

2021-11-21 09:57 UTC, mist962 requested changes

2021-11-21 09:57 UTC, mist962 commented on app/build.gradle
> +    }
2 раза повторешь, удали в 17 строке

2021-11-21 09:57 UTC, mist962 commented on app/build.gradle
> +
2 подрят пустые строки не дело

2021-11-21 09:57 UTC, mist962 commented on app/src/main/java/com/example/mynewsapp/login_and_registration/LoginFragment.kt
> +
epmty line

2021-11-21 09:57 UTC, mist962 commented on app/src/main/java/com/example/mynewsapp/login_and_registration/RegistrationFragment.kt
> +        userViewModel = ViewModelProvider(this).get(UserViewModel::class.java)
это сдолжно быть под строкой binding = Fragme...

2021-11-21 09:57 UTC, mist962 commented on app/src/main/java/com/example/mynewsapp/login_and_registration/RegistrationFragment.kt
> +                if(userLogin.text?.toString()?.trim().equals("") ||
слишком непонятный иф, создай функцию внизу, которая будет dозвращаеть Boolean и содеожать это условие, дай нормальное название этой функции и вставь сюда

2021-11-21 09:57 UTC, mist962 commented on app/src/main/java/com/example/mynewsapp/login_and_registration/RegistrationFragment.kt
> +                else if(switchAgree.isChecked.equals(false) == true)
всем ифам добавь {}

2021-11-21 09:57 UTC, mist962 commented on app/src/main/java/room/User.kt
> +    var Id: Int? = null
это должно быть в конструкторе а не в теле

2021-11-21 09:57 UTC, mist962 commented on app/src/main/java/room/User.kt
> +@Entity(tableName = "Login")
login_table должно быть название

2021-11-21 15:07 UTC, mist962 approved these changes

2021-11-21 15:08 UTC, merged